/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "BusStation"
 * 	found in "BusStation.asn"
 */

#ifndef	_BusStationInformation_H_
#define	_BusStationInformation_H_


#include <asn_application.h>

/* Including external dependencies */
#include "BusStationNum.h"
#include <OCTET_STRING.h>
#include "Position3D.h"
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct BusInfo;
struct Ingress;
struct StopArea;

/* BusStationInformation */
typedef struct BusStationInformation {
	BusStationNum_t	 id;
	OCTET_STRING_t	*name	/* OPTIONAL */;
	Position3D_t	 refPos;
	struct busInfo {
		A_SEQUENCE_OF(struct BusInfo) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} busInfo;
	struct ingress {
		A_SEQUENCE_OF(struct Ingress) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} ingress;
	struct stopArea {
		A_SEQUENCE_OF(struct StopArea) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} stopArea;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} BusStationInformation_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_BusStationInformation;
extern asn_SEQUENCE_specifics_t asn_SPC_BusStationInformation_specs_1;
extern asn_TYPE_member_t asn_MBR_BusStationInformation_1[6];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "BusInfo.h"
#include "Ingress.h"
#include "StopArea.h"

#endif	/* _BusStationInformation_H_ */
#include <asn_internal.h>
