/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "IPPR"
 * 	found in "IPPR.asn"
 */

#ifndef	_IntersectionPriorityPassingRequest_H_
#define	_IntersectionPriorityPassingRequest_H_


#include <asn_application.h>

/* Including external dependencies */
#include "MsgCount.h"
#include <OCTET_STRING.h>
#include "DSecond.h"
#include "DrivingIntention.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* IntersectionPriorityPassingRequest */
typedef struct IntersectionPriorityPassingRequest {
	MsgCount_t	 msgCnt;
	OCTET_STRING_t	 id;
	OCTET_STRING_t	*plateNo	/* OPTIONAL */;
	DSecond_t	 secMark;
	DrivingIntention_t	 drivingIntention;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} IntersectionPriorityPassingRequest_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_IntersectionPriorityPassingRequest;
extern asn_SEQUENCE_specifics_t asn_SPC_IntersectionPriorityPassingRequest_specs_1;
extern asn_TYPE_member_t asn_MBR_IntersectionPriorityPassingRequest_1[5];

#ifdef __cplusplus
}
#endif

#endif	/* _IntersectionPriorityPassingRequest_H_ */
#include <asn_internal.h>
