/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "RSV"
 * 	found in "RSV.asn"
 */

#ifndef	_RoadSideVideo_H_
#define	_RoadSideVideo_H_


#include <asn_application.h>

/* Including external dependencies */
#include "MsgCount.h"
#include "MinuteOfTheYear.h"
#include <OCTET_STRING.h>
#include "Position3D.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct RTEList;
struct RTSList;

/* RoadSideVideo */
typedef struct RoadSideVideo {
	MsgCount_t	 msgCnt;
	MinuteOfTheYear_t	*moy	/* OPTIONAL */;
	OCTET_STRING_t	 id;
	Position3D_t	 refPos;
	struct RTEList	*rtes	/* OPTIONAL */;
	struct RTSList	*rtss	/* OPTIONAL */;
	OCTET_STRING_t	 video;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RoadSideVideo_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RoadSideVideo;
extern asn_SEQUENCE_specifics_t asn_SPC_RoadSideVideo_specs_1;
extern asn_TYPE_member_t asn_MBR_RoadSideVideo_1[7];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "RTEList.h"
#include "RTSList.h"

#endif	/* _RoadSideVideo_H_ */
#include <asn_internal.h>
