// ==========================================================================
// Copyright (C) 2018 - 2021 Beijing 51WORLD Digital Twin Technology Co., Ltd. 
// , and/or its licensors.  All rights reserved.
//
// The coded instructions, statements, computer programs, and/or related 
// material (collectively the "Data") in these files contain unpublished
// information proprietary to Beijing 51WORLD Digital Twin Technology Co., Ltd. 
// ("51WORLD") and/or its licensors,  which is protected by the People's 
// Republic of China and/or other countries copyright law and by 
// international treaties.
//
// The Data may not be disclosed or distributed to third parties or be
// copied or duplicated, in whole or in part, without the prior written
// consent of 51WORLD.
//
// The copyright notices in the Software and this entire statement,
// including the above license grant, this restriction and the following
// disclaimer, must be included in all copies of the Software, in whole
// or in part, and all derivative works of the Software, unless such copies
// or derivative works are solely in the form of machine-executable object
// code generated by a source language processor.

// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND.
// 51WORLD DOES NOT MAKE AND HEREBY DISCLAIMS ANY EXPRESS OR IMPLIED
// WARRANTIES INCLUDING, BUT NOT LIMITED TO, THE WARRANTIES OF
// NON-INFRINGEMENT, MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE,
// OR ARISING FROM A COURSE OF DEALING, USAGE, OR TRADE PRACTICE. IN NO
// EVENT WILL 51WORLD AND/OR ITS LICENSORS BE LIABLE FOR ANY LOST
// REVENUES, DATA, OR PROFITS, OR SPECIAL, DIRECT, INDIRECT, OR
// CONSEQUENTIAL DAMAGES, EVEN IF 51WORLD AND/OR ITS LICENSORS HAS
// BEEN ADVISED OF THE POSSIBILITY OR PROBABILITY OF SUCH DAMAGES.
// ==========================================================================
#pragma once
#ifndef WITHOUT_V2X
#ifdef BUILD_SIMONE_API
#if defined(WIN32) || defined(_WIN32)
#define SIMONE_API __declspec(dllexport)
#elif defined(__linux__) || defined(__linux)
#define SIMONE_API __attribute__((visibility("default")))
#endif
#else
#define SIMONE_API
#endif

#include <string>
#include "Service/SimOneIOStruct.h"

//namespace HDMapStandalone
//{
//    struct MLaneInfo;
//	struct MLaneLink;
//}

#ifdef __cplusplus
extern "C"
{
#endif

	namespace SimOneAPI {

		/*!
		获得对应车辆编号V2X中的UPER编码之后的v2x消息
		\li function:
		*	GetV2XInfo
		\li brief:
		*	Get V2X UPER ASN Message
		@param[in]
		*	mainVehicleId: Id of the main vehicle
		@param[in]
		*	sensorId: Id of the obu sensor
		@param[in]
		*	infoType: type of the obu message witch matches with enum ESimOne_V2X_MessageFrame_PR
		@param[out]
		*	pDetections:  V2XASN data
		@return
		*	Success or not
		*/
		SIMONE_API bool GetV2XInfo(const char* mainVehicleId, const char* sensorId, int infoType, SimOne_Data_V2XNFS *pDetections);

		/*!
		获得对应车辆编号V2X中的UPER编码之后的v2x消息更新回调
		\li function:
		*	SetV2XInfoUpdateCB
		\li brief:
		*	Register mainVehicle V2X UPER ASN Message CallBack
		@param
		*	mainVehicleId: Id of the main vehicle
		@param[out]
		*	cb: callback func applying for obu message of the traffic-vehicle
		*	param[out]:
		*	mainVehicleId: Id of the main vehicle
		*	sensorId: Id of the obu sensor
		*	pDetections:  V2XASN data
		@return
		*	Success or not
		*/
		SIMONE_API bool SetV2XInfoUpdateCB(void(*cb)(const char* mainVehicleId, const char* sensorId, SimOne_Data_V2XNFS *pDetections));
	}
#ifdef __cplusplus
}
#endif
#endif
